name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.36.96.0 << 'EOF'
          cd ~/WebServer
          git pull origin master
          docker compose down
          docker compose up -d --build
        EOF